/* tslint:disable */
/* eslint-disable */
/**
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * Accreditation model
 */
export interface Accreditation {
    /**
     * Unique identifier for the accreditation
     */
    'id'?: number;
    /**
     * Name of the associated organisation
     */
    'associated_organisation_name'?: string;
    /**
     * ID string for the accreditation
     */
    'id_string'?: string;
    /**
     * Date when the accreditation was issued
     */
    'issue_date'?: string;
    /**
     * Date when the accreditation expires
     */
    'expiry_date'?: string;
    /**
     * Timestamp when the accreditation was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the accreditation was last updated
     */
    'updated_at'?: string;
}
/**
 * Action Log model
 */
export interface ActionLog {
    /**
     * Model primary key
     */
    'id'?: number;
    /**
     * Type of the entity associated with the action log
     */
    'entity_type'?: string;
    /**
     * ID of the entity associated with the action log
     */
    'entity_id'?: number;
    /**
     * Description of the action performed
     */
    'action'?: string;
    /**
     * Timestamp when the action was completed (nullable)
     */
    'completed_at'?: string;
}
/**
 * Affiliation model
 */
export interface Affiliation {
    /**
     * Model primary key
     */
    'id'?: number;
    'created_at'?: string;
    'updated_at'?: string;
    /**
     * Organisational link
     */
    'organisation_id'?: number;
    /**
     * Member ID UUID
     */
    'member_id'?: string;
    /**
     * Textual representation of affiliation relationship
     */
    'relationship'?: string;
    /**
     * Date affiliation commenced
     */
    'from'?: string;
    /**
     * Date affiliation concluded
     */
    'to'?: string;
    /**
     * Department worked during affiliation
     */
    'department'?: string;
    /**
     * Role held during affiliation
     */
    'role'?: string;
    /**
     * Professional email held during affiliation
     */
    'email'?: string;
    /**
     * The ROR.org identifier for this affiliation institute
     */
    'ror'?: string;
    /**
     * The Registry primary key associated with this affiliation
     */
    'registry_id'?: number;
    /**
     * Flag indicating if affiliation is for the current employer
     */
    'current_employer'?: boolean;
    /**
     * Unique verification code issued for confirmation
     */
    'verification_code'?: string;
    /**
     * Timestamp when verification code was sent
     */
    'verification_sent_at'?: string;
    /**
     * Timestamp when verification was confirmed
     */
    'verification_confirmed_at'?: string;
    /**
     * Flag indicating if affiliation is verified
     */
    'is_verified'?: boolean;
}
/**
 * Charity model
 */
export interface Charity {
    /**
     * Unique identifier for the charity
     */
    'id'?: number;
    /**
     * Registration ID of the charity
     */
    'registration_id'?: string;
    /**
     * Name of the charity
     */
    'name'?: string;
    /**
     * Website URL of the charity
     */
    'website'?: string;
    /**
     * First line of the charity\'s address
     */
    'address_1'?: string;
    /**
     * Second line of the charity\'s address
     */
    'address_2'?: string;
    /**
     * Town where the charity is located
     */
    'town'?: string;
    /**
     * County where the charity is located
     */
    'county'?: string;
    /**
     * Country where the charity is located
     */
    'country'?: string;
    /**
     * Postcode of the charity\'s address
     */
    'postcode'?: string;
}
/**
 * Custodian model
 */
export interface Custodian {
    /**
     * Model primary key
     */
    'id'?: number;
    'created_at'?: string;
    'updated_at'?: string;
    'name'?: string;
    /**
     * A unique identifier for Custodian\'s within SOURSD
     */
    'unique_identifier'?: string;
    'contact_email'?: string;
    'enabled'?: boolean;
    'invite_accepted_at'?: string;
    'invite_sent_at'?: string;
    'idvt_required'?: boolean;
    'gateway_app_id'?: string;
    'gateway_client_id'?: string;
    'client_id'?: string;
}
/**
 * Custodian approval status for a project organisation
 */
export interface CustodianHasProjectOrganisation {
    'id'?: number;
    /**
     * ID of the project organisation
     */
    'project_has_organisation_id': number;
    /**
     * ID of the custodian
     */
    'custodian_id': number;
    /**
     * Approval flag
     */
    'approved'?: boolean | null;
    /**
     * Optional comment
     */
    'comment'?: string | null;
    'created_at'?: string;
    'updated_at'?: string;
    'projectOrganisation'?: ProjectHasOrganisation;
    'custodian'?: Custodian;
}
export interface CustodianHasProjectUser {
    'id'?: number;
    'project_has_user_id'?: number;
    'custodian_id'?: number;
    'created_at'?: string;
    'updated_at'?: string;
    'projectHasUser'?: ProjectHasUser;
}
/**
 * CustodianModelConfig model
 */
export interface CustodianModelConfig {
    /**
     * Model primary key
     */
    'id'?: number;
    'created_at'?: string;
    'updated_at'?: string;
    'entity_model_id'?: number;
    'active'?: boolean;
    'custodian_id'?: number;
}
/**
 * CustodianUser model
 */
export interface CustodianUser {
    /**
     * Model primary key
     */
    'id'?: number;
    /**
     * Custodian primary key
     */
    'custodian_id'?: number;
    'created_at'?: string;
    'updated_at'?: string;
    'first_name'?: string;
    'last_name'?: string;
    'email'?: string;
}
export interface CustodianUserBulkStore201Response {
    'message'?: string;
    'data'?: Array<number>;
}
export interface CustodianUserBulkStore500Response {
    'message'?: string;
}
export interface CustodianUserBulkStoreRequest {
    'users'?: Array<CustodianUserBulkStoreRequestUsersInner>;
}
export interface CustodianUserBulkStoreRequestUsersInner {
    'first_name'?: string;
    'last_name'?: string;
    'email'?: string;
    'permission'?: CustodianUserBulkStoreRequestUsersInnerPermissionEnum;
}

export const CustodianUserBulkStoreRequestUsersInnerPermissionEnum = {
    CustodianAdmin: 'CUSTODIAN_ADMIN',
    CustodianApprover: 'CUSTODIAN_APPROVER',
} as const;

export type CustodianUserBulkStoreRequestUsersInnerPermissionEnum = typeof CustodianUserBulkStoreRequestUsersInnerPermissionEnum[keyof typeof CustodianUserBulkStoreRequestUsersInnerPermissionEnum];

/**
 * Model representing the relationship between Custodian Users and Permissions
 */
export interface CustodianUserHasPermission {
    /**
     * ID of the custodian user
     */
    'custodian_user_id'?: number;
    /**
     * ID of the permission
     */
    'permission_id'?: number;
}
/**
 * Model representing webhook receivers for custodians
 */
export interface CustodianWebhookReceiver {
    /**
     * Unique identifier for the webhook receiver
     */
    'id'?: number;
    /**
     * ID of the custodian associated with the webhook receiver
     */
    'custodian_id'?: number;
    /**
     * URL of the webhook receiver
     */
    'url'?: string;
    /**
     * ID of the webhook event associated with the receiver
     */
    'webhook_event'?: number;
    /**
     * Timestamp when the webhook receiver was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the webhook receiver was last updated
     */
    'updated_at'?: string;
}
/**
 * Model representing debug logs
 */
export interface DebugLog {
    /**
     * Unique identifier for the debug log
     */
    'id'?: number;
    /**
     * Class name where the log was generated
     */
    'class'?: string;
    /**
     * Log message
     */
    'log'?: string;
    /**
     * Timestamp when the log was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the log was last updated
     */
    'updated_at'?: string;
}
/**
 * Model representing decision models
 */
export interface DecisionModel {
    /**
     * Unique identifier for the decision model
     */
    'id'?: number;
    /**
     * Type of the model associated with the decision
     */
    'model_type': string;
    /**
     * Conditions for the decision model
     */
    'conditions': string;
    /**
     * Class defining the rules for the decision model
     */
    'rule_class': string;
    /**
     * Description of the decision model
     */
    'description'?: string;
    /**
     * ID of the entity model type associated with the decision
     */
    'entity_model_type_id'?: number;
    /**
     * Timestamp when the decision model was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the decision model was last updated
     */
    'updated_at'?: string;
}
/**
 * Model representing departments
 */
export interface Department {
    /**
     * Unique identifier for the department
     */
    'id'?: number;
    /**
     * Name of the department
     */
    'name'?: string;
    /**
     * Category of the department
     */
    'category'?: string;
    /**
     * Timestamp when the department was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the department was last updated
     */
    'updated_at'?: string;
}
/**
 * Model representing education records
 */
export interface Education {
    /**
     * Unique identifier for the education record
     */
    'id'?: number;
    /**
     * Title of the education qualification
     */
    'title'?: string;
    /**
     * Start date of the education qualification
     */
    'from'?: string;
    /**
     * End date of the education qualification
     */
    'to'?: string;
    /**
     * Name of the educational institute
     */
    'institute_name'?: string;
    /**
     * Address of the educational institute
     */
    'institute_address'?: string;
    /**
     * Identifier for the educational institute
     */
    'institute_identifier'?: string;
    /**
     * Source of the education record
     */
    'source'?: string;
    /**
     * ID of the registry associated with the education record
     */
    'registry_id'?: number;
    /**
     * Timestamp when the education record was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the education record was last updated
     */
    'updated_at'?: string;
}
/**
 * Model representing endorsements
 */
export interface Endorsement {
    /**
     * Unique identifier for the endorsement
     */
    'id'?: number;
    /**
     * ID of the user who reported the endorsement
     */
    'reported_by'?: number;
    /**
     * Optional comment provided by the reporter
     */
    'comment'?: string;
    /**
     * ID of the entity the endorsement is raised against
     */
    'raised_against'?: number;
    /**
     * Timestamp when the endorsement was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the endorsement was last updated
     */
    'updated_at'?: string;
}
/**
 * Model representing entity models
 */
export interface EntityModel {
    /**
     * Unique identifier for the entity model
     */
    'id'?: number;
    /**
     * Name of the entity model
     */
    'name'?: string;
    /**
     * Description of the entity model
     */
    'description'?: string;
    /**
     * ID of the entity model type associated with this model
     */
    'entity_model_type_id'?: number;
    /**
     * Indicates whether the model calls a file
     */
    'calls_file'?: boolean;
    /**
     * Path to the file called by the model
     */
    'file_path'?: string;
    /**
     * Indicates whether the model calls an operation
     */
    'calls_operation'?: boolean;
    /**
     * Operation called by the model
     */
    'operation'?: string;
    /**
     * Indicates whether the model is active (1 for active, 0 for inactive)
     */
    'active'?: number;
    /**
     * Timestamp when the entity model was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the entity model was last updated
     */
    'updated_at'?: string;
}
/**
 * Model representing types of entity models
 */
export interface EntityModelType {
    /**
     * Unique identifier for the entity model type
     */
    'id'?: number;
    /**
     * Name of the entity model type
     */
    'name'?: string;
    /**
     * Timestamp when the entity model type was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the entity model type was last updated
     */
    'updated_at'?: string;
}
/**
 * Model representing experiences
 */
export interface Experience {
    /**
     * Unique identifier for the experience
     */
    'id'?: number;
    /**
     * ID of the project associated with the experience
     */
    'project_id'?: number;
    /**
     * Start date of the experience
     */
    'from'?: string;
    /**
     * End date of the experience
     */
    'to'?: string;
    /**
     * ID of the organisation associated with the experience
     */
    'organisation_id'?: number;
    /**
     * Timestamp when the experience was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the experience was last updated
     */
    'updated_at'?: string;
}
export interface FeatureIndex200Response {
    'message'?: string;
    'data'?: FeatureIndex200ResponseData;
}
export interface FeatureIndex200ResponseData {
    'id'?: number;
    'name'?: string;
    'scope'?: string;
    'value'?: boolean;
    'description'?: string;
    'created_at'?: string;
    'updated_at'?: string;
}
export interface FeatureIndex404Response {
    'message'?: string;
}
/**
 * Model representing historical records
 */
export interface History {
    /**
     * Unique identifier for the history record
     */
    'id'?: number;
    /**
     * ID of the affiliation associated with the history record
     */
    'affiliation_id'?: number;
    /**
     * ID of the endorsement associated with the history record
     */
    'endorsement_id'?: number;
    /**
     * ID of the infringement associated with the history record
     */
    'infringement_id'?: number;
    /**
     * ID of the project associated with the history record
     */
    'project_id'?: number;
    /**
     * ID of the access key associated with the history record
     */
    'access_key_id'?: number;
    /**
     * Identifier for the custodian associated with the history record
     */
    'custodian_identifier'?: string;
    /**
     * Hash of the ledger associated with the history record
     */
    'ledger_hash'?: string;
    /**
     * Timestamp when the history record was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the history record was last updated
     */
    'updated_at'?: string;
}
/**
 * Model representing IDVT plugins
 */
export interface IDVTPlugin {
    /**
     * Unique identifier for the IDVT plugin
     */
    'id'?: number;
    /**
     * Function name of the plugin
     */
    'function'?: string;
    /**
     * Arguments passed to the plugin function
     */
    'args'?: string;
    /**
     * Configuration settings for the plugin
     */
    'config'?: string;
    /**
     * Indicates whether the plugin is enabled (1 for enabled, 0 for disabled)
     */
    'enabled'?: number;
    /**
     * Timestamp when the plugin was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the plugin was last updated
     */
    'updated_at'?: string;
}
/**
 * Model representing identity records
 */
export interface Identity {
    /**
     * Unique identifier for the identity record
     */
    'id'?: number;
    /**
     * ID of the registry associated with the identity record
     */
    'registry_id'?: number;
    /**
     * First line of the address
     */
    'address_1'?: string;
    /**
     * Second line of the address
     */
    'address_2'?: string;
    /**
     * Town of the address
     */
    'town'?: string;
    /**
     * County of the address
     */
    'county'?: string;
    /**
     * Country of the address
     */
    'country'?: string;
    /**
     * Postcode of the address
     */
    'postcode'?: string;
    /**
     * Date of birth
     */
    'dob'?: string;
    /**
     * Indicates whether IDVT was successful (1 for success, 0 for failure)
     */
    'idvt_success'?: number;
    /**
     * Identification number from IDVT
     */
    'idvt_identification_number'?: string;
    /**
     * Type of document used for IDVT
     */
    'idvt_document_type'?: string;
    /**
     * Document number used for IDVT
     */
    'idvt_document_number'?: string;
    /**
     * Country of the document used for IDVT
     */
    'idvt_document_country'?: string;
    /**
     * Validity date of the document used for IDVT
     */
    'idvt_document_valid_until'?: string;
    /**
     * ID of the IDVT attempt
     */
    'idvt_attempt_id'?: string;
    /**
     * Context ID for IDVT
     */
    'idvt_context_id'?: string;
    /**
     * Date of birth on the document used for IDVT
     */
    'idvt_document_dob'?: string;
    /**
     * Context of the IDVT process
     */
    'idvt_context'?: string;
    /**
     * Timestamp when IDVT was completed
     */
    'idvt_completed_at'?: string;
    /**
     * Result text of the IDVT process
     */
    'idvt_result_text'?: string;
    /**
     * Timestamp when IDVT was started
     */
    'idvt_started_at'?: string;
    /**
     * Timestamp when the identity record was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the identity record was last updated
     */
    'updated_at'?: string;
    /**
     * Timestamp when the identity record was deleted
     */
    'deleted_at'?: string;
}
/**
 * Model representing infringements
 */
export interface Infringement {
    /**
     * Unique identifier for the infringement
     */
    'id'?: number;
    /**
     * ID of the user who reported the infringement
     */
    'reported_by'?: number;
    /**
     * Optional comment provided by the reporter
     */
    'comment'?: string;
    /**
     * ID of the entity the infringement is raised against
     */
    'raised_against'?: number;
    /**
     * Timestamp when the infringement was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the infringement was last updated
     */
    'updated_at'?: string;
}
/**
 * Pivot model representing the relationship between infringements and resolutions
 */
export interface InfringementHasResolution {
    /**
     * ID of the infringement
     */
    'infringement_id'?: number;
    /**
     * ID of the resolution
     */
    'resolution_id'?: number;
}
/**
 * Model representing files
 */
export interface ModelFile {
    /**
     * Unique identifier for the file
     */
    'id'?: number;
    /**
     * Name of the file
     */
    'name'?: string;
    /**
     * Type of the file
     */
    'type'?: string;
    /**
     * Path to the file
     */
    'path'?: string;
    /**
     * Status of the file
     */
    'status'?: string;
    /**
     * Timestamp when the file was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the file was last updated
     */
    'updated_at'?: string;
}
/**
 * Model representing the state of a model
 */
export interface ModelState {
    /**
     * Unique identifier for the model state
     */
    'id'?: number;
    /**
     * ID of the state associated with the model state
     */
    'state_id'?: number;
    /**
     * Type of the model associated with the state
     */
    'stateable_type'?: string;
    /**
     * ID of the model associated with the state
     */
    'stateable_id'?: number;
    /**
     * Timestamp when the model state was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the model state was last updated
     */
    'updated_at'?: string;
}
/**
 * Model representing ONS files
 */
export interface ONSFile {
    /**
     * Unique identifier for the ONS file
     */
    'id'?: number;
    /**
     * Name of the ONS file
     */
    'name'?: string;
    /**
     * Path to the ONS file
     */
    'path'?: string;
    /**
     * Status of the ONS file
     */
    'status'?: string;
    /**
     * Timestamp when the ONS file was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the ONS file was last updated
     */
    'updated_at'?: string;
}
/**
 * Organisation model
 */
export interface Organisation {
    /**
     * Model primary key
     */
    'id'?: number;
    'created_at'?: string;
    'updated_at'?: string;
    'organisation_name'?: string;
    'address_1'?: string;
    'address_2'?: string;
    'town'?: string;
    'county'?: string;
    'country'?: string;
    'postcode'?: string;
    'lead_applicant_organisation_name'?: string;
    'lead_applicant_email'?: string;
    'organisation_unique_id'?: string;
    'applicant_names'?: string;
    'funders_and_sponsors'?: string;
    'sub_license_arrangements'?: string;
    'verified'?: boolean;
    'dsptk_ods_code'?: string;
    'dsptk_certified'?: boolean;
    'dsptk_expiry_date'?: string;
    'iso_27001_certified'?: boolean;
    'iso_27001_certification_num'?: string;
    'iso_expiry_date'?: string;
    'ce_certified'?: boolean;
    'ce_certification_num'?: string;
    'ce_expiry_date'?: string;
    'ce_plus_certified'?: boolean;
    'ce_plus_certification_num'?: string;
    'ce_plus_expiry_date'?: string;
    'idvt_result'?: number;
    'idvt_result_perc'?: number;
    'idvt_errors'?: string;
    'idvt_completed_at'?: string;
    'companies_house_no'?: string;
    'sector_id'?: number;
    /**
     * ROR.org identification for Research Organisations
     */
    'ror_id'?: string;
    'website'?: string;
    /**
     * Declaration of small/medium business
     */
    'smb_status'?: boolean;
    /**
     * Organisation size. Integer denotes list index rather than absolute value
     */
    'organisation_size'?: number;
    /**
     * Unclaimed
     */
    'unclaimed'?: boolean;
    /**
     * Whether this Organisation has been approved to use the system or not
     */
    'system_approved'?: boolean;
    'ods_id'?: string;
    'dsptk_status'?: string;
    'dsptk_date_last_published'?: string;
    'ico_registration_id'?: string;
    'ico_date_registered'?: string;
    'ico_expiry_date'?: string;
}
/**
 * Pivot model representing the relationship between organisations and charities
 */
export interface OrganisationHasCharity {
    /**
     * Unique identifier for the organisation-charity relationship
     */
    'id'?: number;
    /**
     * ID of the organisation
     */
    'organisation_id'?: number;
    /**
     * ID of the charity
     */
    'charity_id'?: number;
}
/**
 * Pivot model representing the relationship between organisations, custodians, and permissions
 */
export interface OrganisationHasCustodianPermission {
    /**
     * ID of the organisation
     */
    'organisation_id'?: number;
    /**
     * ID of the permission
     */
    'permission_id'?: number;
    /**
     * ID of the custodian
     */
    'custodian_id'?: number;
}
/**
 * Pivot model representing the relationship between organisations and departments
 */
export interface OrganisationHasDepartment {
    /**
     * ID of the organisation
     */
    'organisation_id'?: number;
    /**
     * ID of the department
     */
    'department_id'?: number;
}
/**
 * Pivot model representing the relationship between organisations and files
 */
export interface OrganisationHasFile {
    /**
     * ID of the organisation
     */
    'organisation_id'?: number;
    /**
     * ID of the file
     */
    'file_id'?: number;
}
/**
 * Pivot model representing the relationship between organisations and subsidiaries
 */
export interface OrganisationHasSubsidiary {
    /**
     * ID of the organisation
     */
    'organisation_id'?: number;
    /**
     * ID of the subsidiary
     */
    'subsidiary_id'?: number;
}
/**
 * Model representing pending invites
 */
export interface PendingInvite {
    /**
     * Unique identifier for the pending invite
     */
    'id'?: number;
    /**
     * ID of the user associated with the invite
     */
    'user_id'?: number;
    /**
     * ID of the organisation associated with the invite
     */
    'organisation_id'?: number;
    /**
     * Status of the invite
     */
    'status'?: string;
    /**
     * Timestamp when the invite was accepted
     */
    'invite_accepted_at'?: string;
    /**
     * Timestamp when the invite was sent
     */
    'invite_sent_at'?: string;
    /**
     * Unique code for the invite
     */
    'invite_code'?: string;
    /**
     * Timestamp when the invite record was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the invite record was last updated
     */
    'updated_at'?: string;
}
/**
 * Model representing permissions
 */
export interface Permission {
    /**
     * Unique identifier for the permission
     */
    'id'?: number;
    /**
     * Name of the permission
     */
    'name'?: string;
    /**
     * Indicates whether the permission is enabled
     */
    'enabled'?: boolean;
    /**
     * Description of the permission
     */
    'description'?: string;
    /**
     * Timestamp when the permission was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the permission was last updated
     */
    'updated_at'?: string;
}
/**
 * Model representing professional registrations
 */
export interface ProfessionalRegistration {
    /**
     * Unique identifier for the professional registration
     */
    'id'?: number;
    /**
     * Member ID associated with the professional registration
     */
    'member_id'?: string;
    /**
     * Name of the professional registration
     */
    'name'?: string;
    /**
     * Timestamp when the professional registration was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the professional registration was last updated
     */
    'updated_at'?: string;
}
/**
 * Project model
 */
export interface Project {
    /**
     * Model primary key
     */
    'id'?: number;
    'title'?: string;
    'unique_id'?: string;
    'lay_summary'?: string;
    /**
     * A unique identifier for Custodian\'s within SOURSD
     */
    'public_benefit'?: string;
    'request_category_type'?: string;
    'technical_summary'?: string;
    'other_approval_commitees'?: string;
    'start_date'?: string;
    'end_date'?: string;
}
/**
 * ProjectDetail model
 */
export interface ProjectDetail {
    /**
     * Model primary key
     */
    'id'?: number;
    'created_at'?: string;
    'updated_at'?: string;
    /**
     * Primary key of associated Project for this ProjectDetail
     */
    'project_id'?: number;
    'datasets'?: Array<string>;
    'other_approval_committees'?: Array<string>;
    'data_sensitivity_level'?: string;
    'legal_basis_for_data_article6'?: string;
    'duty_of_confidentiality'?: boolean;
    'national_data_optout'?: boolean;
    'request_frequency'?: ProjectDetailRequestFrequencyEnum;
    'dataset_linkage_description'?: string;
    'data_minimisation'?: string;
    'data_use_description'?: string;
    'access_date'?: string;
    'access_type'?: number;
    'data_privacy'?: string;
    'research_outputs'?: object;
    'data_assets'?: string;
}

export const ProjectDetailRequestFrequencyEnum = {
    OneOff: 'ONE-OFF',
    Recurring: 'RECURRING',
} as const;

export type ProjectDetailRequestFrequencyEnum = typeof ProjectDetailRequestFrequencyEnum[keyof typeof ProjectDetailRequestFrequencyEnum];

/**
 * Pivot model representing the relationship between projects and custodians
 */
export interface ProjectHasCustodian {
    /**
     * Unique identifier for the project-custodian relationship
     */
    'id'?: number;
    /**
     * ID of the project
     */
    'project_id'?: number;
    /**
     * ID of the custodian
     */
    'custodian_id'?: number;
    /**
     * Indicates whether the custodian is approved for the project (1 for approved, 0 for not approved)
     */
    'approved'?: number;
}
/**
 * Relation between a project and an organisation
 */
export interface ProjectHasOrganisation {
    'id'?: number;
    /**
     * ID of the related project
     */
    'project_id': number;
    /**
     * ID of the related organisation
     */
    'organisation_id': number;
    'organisation'?: Organisation;
    'project'?: Project;
}
/**
 * Pivot model representing the relationship between projects and roles
 */
export interface ProjectHasRole {
    /**
     * ID of the project
     */
    'project_id'?: number;
    /**
     * ID of the project role
     */
    'project_role_id'?: number;
}
export interface ProjectHasUser {
    'project'?: Project;
    'role'?: ProjectRole;
    'affiliation'?: Affiliation;
}
/**
 * ProjectRole model
 */
export interface ProjectRole {
    'id'?: number;
    'created_at'?: string;
    'updated_at'?: string;
    'name'?: string;
}
export interface ProjectUsersBulkInviteProjectUsersRequest {
    'projectId': number;
    'users': Array<ProjectUsersBulkInviteProjectUsersRequestUsersInner>;
}
export interface ProjectUsersBulkInviteProjectUsersRequestUsersInner {
    'firstName'?: string;
    'lastName'?: string;
    'emailAddress'?: string;
    'projectRole'?: ProjectUsersBulkInviteProjectUsersRequestUsersInnerProjectRoleEnum;
    'organisationId'?: number;
}

export const ProjectUsersBulkInviteProjectUsersRequestUsersInnerProjectRoleEnum = {
    PrincipalInvestigatorPi: 'Principal Investigator (PI)',
    CoInvestigatorCoISubInvestigatorSubI: 'Co-Investigator (Co-I) / Sub-Investigator (Sub-I)',
    DataAnalyst: 'Data Analyst',
    DataEngineer: 'Data Engineer',
    Postdoc: 'Postdoc',
    ResearchFellow: 'Research Fellow',
    Researcher: 'Researcher',
    Student: 'Student',
} as const;

export type ProjectUsersBulkInviteProjectUsersRequestUsersInnerProjectRoleEnum = typeof ProjectUsersBulkInviteProjectUsersRequestUsersInnerProjectRoleEnum[keyof typeof ProjectUsersBulkInviteProjectUsersRequestUsersInnerProjectRoleEnum];

export interface QueryQuery200Response {
    'message'?: string;
    'data'?: QueryQuery200ResponseData;
}
export interface QueryQuery200ResponseData {
    'user'?: QueryQuery200ResponseDataUser;
    'registry'?: QueryQuery200ResponseDataRegistry;
    /**
     * Projects the queried user is linked to, scoped to the requesting custodian
     */
    'projects'?: Array<QueryQuery200ResponseDataProjectsInner>;
}
export interface QueryQuery200ResponseDataProjectsInner {
    'project_id'?: number;
    'project_title'?: string;
    'project_user_validation_status'?: string | null;
}
/**
 * The matched Registry record
 */
export interface QueryQuery200ResponseDataRegistry {
    'id'?: number;
    'created_at'?: string;
    'updated_at'?: string;
    'deleted_at'?: string;
    'digi_ident'?: string;
    'dl_ident'?: string;
    'pp_ident'?: string;
    'verified'?: number;
    /**
     * Training records linked to the registry
     */
    'training'?: Array<Training>;
    /**
     * History records linked to the registry, each with its related affiliation and project
     */
    'history'?: Array<QueryQuery200ResponseDataRegistryAllOfHistoryInner>;
}
export interface QueryQuery200ResponseDataRegistryAllOfHistoryInner {
    /**
     * Unique identifier for the history record
     */
    'id'?: number;
    /**
     * ID of the affiliation associated with the history record
     */
    'affiliation_id'?: number;
    /**
     * ID of the endorsement associated with the history record
     */
    'endorsement_id'?: number;
    /**
     * ID of the infringement associated with the history record
     */
    'infringement_id'?: number;
    /**
     * ID of the project associated with the history record
     */
    'project_id'?: number;
    /**
     * ID of the access key associated with the history record
     */
    'access_key_id'?: number;
    /**
     * Identifier for the custodian associated with the history record
     */
    'custodian_identifier'?: string;
    /**
     * Hash of the ledger associated with the history record
     */
    'ledger_hash'?: string;
    /**
     * Timestamp when the history record was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the history record was last updated
     */
    'updated_at'?: string;
    'affiliation'?: Affiliation | null;
    'project'?: Project | null;
}
/**
 * The User record linked to the matched Registry
 */
export interface QueryQuery200ResponseDataUser {
    'id'?: number;
    'first_name'?: string;
    'last_name'?: string;
    'name'?: string;
    'email'?: string;
    'registry_id'?: number;
    'created_at'?: string;
    'updated_at'?: string;
    'user_group'?: string;
    'consent_scrape'?: boolean;
    'orc_id'?: string | null;
    'unclaimed'?: number;
    'feed_source'?: string | null;
    'public_opt_in'?: number;
    'declaration_signed'?: boolean;
    'organisation_id'?: number;
    'orcid_scanning'?: boolean;
    'orcid_scanning_completed_at'?: string | null;
    'is_delegate'?: number;
    'is_org_admin'?: number;
    'custodian_id'?: number | null;
    'custodian_user_id'?: number | null;
    'role'?: string | null;
    'location'?: string | null;
    't_and_c_agreed'?: boolean;
    't_and_c_agreement_date'?: string | null;
    'uksa_registered'?: boolean;
    'is_sro'?: boolean;
    'invited_by'?: number | null;
    'status'?: string;
    'evaluation'?: string | null;
    'identity'?: Identity | null;
}
export interface QueryQuery401Response {
    'message'?: string;
}
export interface QueryQueryRequest {
    /**
     * The Registry\'s digi_ident value
     */
    'ident'?: string;
}
/**
 * Registry model
 */
export interface Registry {
    'id'?: number;
    'created_at'?: string;
    'updated_at'?: string;
    'deleted_at'?: string;
    'digi_ident'?: string;
    'dl_ident'?: string;
    'pp_ident'?: string;
    'verified'?: number;
}
/**
 * Pivot model representing the relationship between registries and accreditations
 */
export interface RegistryHasAccreditation {
    /**
     * ID of the registry
     */
    'registry_id'?: number;
    /**
     * ID of the accreditation
     */
    'accreditation_id'?: number;
}
/**
 * Pivot model representing the relationship between registries and affiliations
 */
export interface RegistryHasAffiliation {
    /**
     * Unique identifier for the registry-affiliation relationship
     */
    'id'?: number;
    /**
     * ID of the registry
     */
    'registry_id'?: number;
    /**
     * ID of the affiliation
     */
    'affiliation_id'?: number;
}
/**
 * Pivot model representing the relationship between registries and educations
 */
export interface RegistryHasEducation {
    /**
     * ID of the registry
     */
    'registry_id'?: number;
    /**
     * ID of the education
     */
    'education_id'?: number;
}
/**
 * Pivot model representing the relationship between registries and files
 */
export interface RegistryHasFile {
    /**
     * ID of the registry
     */
    'registry_id'?: number;
    /**
     * ID of the file
     */
    'file_id'?: string;
}
/**
 * Pivot model representing the relationship between registries and histories
 */
export interface RegistryHasHistory {
    /**
     * ID of the registry
     */
    'registry_id'?: number;
    /**
     * ID of the history
     */
    'history_id'?: number;
}
/**
 * Pivot model representing the relationship between registries and professional registrations
 */
export interface RegistryHasProfessionalRegistration {
    /**
     * Unique identifier for the registry-professional registration relationship
     */
    'id'?: number;
    /**
     * ID of the registry
     */
    'registry_id'?: number;
    /**
     * ID of the professional registration
     */
    'professional_registration_id'?: number;
}
/**
 * Pivot model representing the relationship between registries and trainings
 */
export interface RegistryHasTraining {
    /**
     * ID of the registry
     */
    'registry_id'?: number;
    /**
     * ID of the training
     */
    'training_id'?: number;
}
/**
 * Model representing resolutions
 */
export interface Resolution {
    /**
     * Unique identifier for the resolution
     */
    'id'?: number;
    /**
     * Comment associated with the resolution
     */
    'comment'?: string;
    /**
     * ID of the custodian who resolved the issue
     */
    'custodian_by'?: number;
    /**
     * ID of the registry associated with the resolution
     */
    'registry_id'?: number;
    /**
     * Indicates whether the resolution is resolved
     */
    'resolved'?: boolean;
    /**
     * Timestamp when the resolution was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the resolution was last updated
     */
    'updated_at'?: string;
}
/**
 * Model representing sectors
 */
export interface Sector {
    /**
     * Unique identifier for the sector
     */
    'id'?: number;
    /**
     * Name of the sector
     */
    'name'?: string;
    /**
     * Timestamp when the sector was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the sector was last updated
     */
    'updated_at'?: string;
    /**
     * Timestamp when the sector was deleted
     */
    'deleted_at'?: string;
}
/**
 * Model representing states
 */
export interface State {
    /**
     * Unique identifier for the state
     */
    'id'?: number;
    /**
     * Name of the state
     */
    'name'?: string;
    /**
     * Slug identifier for the state
     */
    'slug'?: string;
    /**
     * Timestamp when the state was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the state was last updated
     */
    'updated_at'?: string;
}
/**
 * Model representing subsidiaries
 */
export interface Subsidiary {
    /**
     * Unique identifier for the subsidiary
     */
    'id'?: number;
    /**
     * Name of the subsidiary
     */
    'name'?: string;
    /**
     * Primary address line of the subsidiary
     */
    'address_1'?: string;
    /**
     * Secondary address line of the subsidiary
     */
    'address_2'?: string;
    /**
     * Town where the subsidiary is located
     */
    'town'?: string;
    /**
     * County where the subsidiary is located
     */
    'county'?: string;
    /**
     * Country where the subsidiary is located
     */
    'country'?: string;
    /**
     * Postcode of the subsidiary
     */
    'postcode'?: string;
    /**
     * Website of the subsidiary
     */
    'website'?: string;
    /**
     * Indicates if the subsidiary is a parent company
     */
    'is_parent'?: number;
}
/**
 * Model representing system configuration settings
 */
export interface SystemConfig {
    /**
     * Unique identifier for the system configuration
     */
    'id'?: number;
    /**
     * Name of the configuration setting
     */
    'name'?: string;
    /**
     * Value of the configuration setting
     */
    'value'?: string;
    /**
     * Description of the configuration setting
     */
    'description'?: string;
    /**
     * Timestamp when the configuration was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the configuration was last updated
     */
    'updated_at'?: string;
}
/**
 * Training model
 */
export interface Training {
    'id'?: number;
    'created_at'?: string;
    'updated_at'?: string;
    'registry_id'?: number;
    'provider'?: string;
    'awarded_at'?: string;
    'expires_at'?: string;
    'expires_in_years'?: number;
    'training_name'?: string;
    'pro_registration'?: number;
}
/**
 * Pivot model representing the relationship between trainings and files
 */
export interface TrainingHasFile {
    /**
     * ID of the training
     */
    'training_id'?: number;
    /**
     * ID of the file
     */
    'file_id'?: number;
}
/**
 * Model representing UKSA live feed data
 */
export interface UksaLiveFeed {
    /**
     * Unique identifier for the UKSA live feed record
     */
    'id'?: number;
    /**
     * First name of the individual
     */
    'first_name'?: string;
    /**
     * Last name of the individual
     */
    'last_name'?: string;
    /**
     * Name of the organisation
     */
    'organisation_name'?: string;
    /**
     * Accreditation number
     */
    'accreditation_number'?: string;
    /**
     * Type of accreditation
     */
    'accreditation_type'?: string;
    /**
     * Expiry date of the accreditation
     */
    'expiry_date'?: string;
    /**
     * Indicates whether the record is public
     */
    'public_record'?: string;
    /**
     * Current stage of the accreditation process
     */
    'stage'?: string;
    /**
     * Timestamp when the record was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the record was last updated
     */
    'updated_at'?: string;
}
/**
 * User model
 */
export interface User {
    'id'?: number;
    'created_at'?: string;
    'updated_at'?: string;
    'first_name'?: string;
    'last_name'?: string;
    'email'?: string;
    'email_verified_at'?: string;
    'consent_scrape'?: boolean;
    'public_opt_in'?: boolean;
    'declaration_signed'?: boolean;
    'organisation_id'?: number;
    'orcid_scanning'?: number;
    'orcid_scanning_completed_at'?: string;
    'location'?: string;
    't_and_c_agreed'?: boolean;
    't_and_c_agreement_date'?: string;
}
/**
 * Pivot model representing the relationship between users, custodians, and permissions
 */
export interface UserHasCustodianPermission {
    /**
     * ID of the user
     */
    'user_id'?: number;
    /**
     * ID of the permission
     */
    'permission_id'?: number;
    /**
     * ID of the custodian
     */
    'custodian_id'?: number;
}
/**
 * Pivot model representing the relationship between users and departments
 */
export interface UserHasDepartments {
    /**
     * ID of the user
     */
    'user_id'?: number;
    /**
     * ID of the department
     */
    'department_id'?: number;
}
/**
 * Model representing validation checks
 */
export interface ValidationCheck {
    /**
     * Unique identifier for the validation check
     */
    'id'?: number;
    /**
     * Name of the validation check
     */
    'name': string;
    /**
     * Description of the validation check
     */
    'description': string;
    /**
     * Context to which the validation check applies
     */
    'applies_to': string;
    /**
     * Indicates whether the validation check is enabled
     */
    'enabled'?: boolean;
    /**
     * Timestamp when the validation check was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the validation check was last updated
     */
    'updated_at'?: string;
    /**
     * Custodian id or null
     */
    'custodian_id'?: number;
}
/**
 * Validation Log model
 */
export interface ValidationLog {
    /**
     * Model primary key
     */
    'id'?: number;
    /**
     * Type of the primary entity associated with the validation log
     */
    'entity_type'?: string;
    /**
     * ID of the primary entity associated with the validation log
     */
    'entity_id'?: number;
    /**
     * Type of the secondary entity associated with the validation log
     */
    'secondary_entity_type'?: string;
    /**
     * ID of the secondary entity associated with the validation log
     */
    'secondary_entity_id'?: number;
    /**
     * Type of the tertiary entity associated with the validation log
     */
    'tertiary_entity_type'?: string;
    /**
     * ID of the tertiary entity associated with the validation log
     */
    'tertiary_entity_id'?: number;
    /**
     * Name of the validation log entry
     */
    'name'?: string;
    /**
     * Timestamp when the validation was completed (nullable)
     */
    'completed_at'?: string;
    /**
     * Whether the validation was manually confirmed
     */
    'manually_confirmed'?: boolean;
}
/**
 * Comments on validation logs
 */
export interface ValidationLogComment {
    /**
     * Model primary key
     */
    'id'?: number;
    /**
     * ID of the associated validation log
     */
    'validation_log_id'?: number;
    /**
     * ID of the user who made the comment
     */
    'user_id'?: number;
    /**
     * The comment text
     */
    'comment'?: string;
    /**
     * Timestamp when the comment was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the comment was last updated
     */
    'updated_at'?: string;
}
export interface VendorWebhookReceiverReceive200Response {
    'message'?: string;
    'data'?: Array<object>;
}
export interface VendorWebhookReceiverReceive400Response {
    'message'?: string;
}
export interface VendorWebhookReceiverReceive500Response {
    'message'?: string;
}
/**
 * Model representing webhook event triggers
 */
export interface WebhookEventTrigger {
    /**
     * Unique identifier for the webhook event trigger
     */
    'id'?: number;
    /**
     * Name of the webhook event trigger
     */
    'name'?: string;
    /**
     * Description of the webhook event trigger
     */
    'description'?: string;
    /**
     * Indicates whether the webhook event trigger is enabled
     */
    'enabled'?: boolean;
    /**
     * Timestamp when the webhook event trigger was created
     */
    'created_at'?: string;
    /**
     * Timestamp when the webhook event trigger was last updated
     */
    'updated_at'?: string;
}

/**
 * CustodianUserApi - axios parameter creator
 */
export const CustodianUserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create multiple CustodianUser entries
         * @summary Create multiple CustodianUser entries
         * @param {CustodianUserBulkStoreRequest} custodianUserBulkStoreRequest Array of CustodianUser definitions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        custodianUserBulkStore: async (custodianUserBulkStoreRequest: CustodianUserBulkStoreRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'custodianUserBulkStoreRequest' is not null or undefined
            assertParamExists('custodianUserBulkStore', 'custodianUserBulkStoreRequest', custodianUserBulkStoreRequest)
            const localVarPath = `/api/v1/custodian_users/bulk`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(custodianUserBulkStoreRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CustodianUserApi - functional programming interface
 */
export const CustodianUserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CustodianUserApiAxiosParamCreator(configuration)
    return {
        /**
         * Create multiple CustodianUser entries
         * @summary Create multiple CustodianUser entries
         * @param {CustodianUserBulkStoreRequest} custodianUserBulkStoreRequest Array of CustodianUser definitions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async custodianUserBulkStore(custodianUserBulkStoreRequest: CustodianUserBulkStoreRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CustodianUserBulkStore201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.custodianUserBulkStore(custodianUserBulkStoreRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CustodianUserApi.custodianUserBulkStore']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CustodianUserApi - factory interface
 */
export const CustodianUserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CustodianUserApiFp(configuration)
    return {
        /**
         * Create multiple CustodianUser entries
         * @summary Create multiple CustodianUser entries
         * @param {CustodianUserBulkStoreRequest} custodianUserBulkStoreRequest Array of CustodianUser definitions
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        custodianUserBulkStore(custodianUserBulkStoreRequest: CustodianUserBulkStoreRequest, options?: RawAxiosRequestConfig): AxiosPromise<CustodianUserBulkStore201Response> {
            return localVarFp.custodianUserBulkStore(custodianUserBulkStoreRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CustodianUserApi - object-oriented interface
 */
export class CustodianUserApi extends BaseAPI {
    /**
     * Create multiple CustodianUser entries
     * @summary Create multiple CustodianUser entries
     * @param {CustodianUserBulkStoreRequest} custodianUserBulkStoreRequest Array of CustodianUser definitions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public custodianUserBulkStore(custodianUserBulkStoreRequest: CustodianUserBulkStoreRequest, options?: RawAxiosRequestConfig) {
        return CustodianUserApiFp(this.configuration).custodianUserBulkStore(custodianUserBulkStoreRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * FeatureApi - axios parameter creator
 */
export const FeatureApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Return a list of Feature entries
         * @summary Feature@index
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        featureIndex: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/features`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FeatureApi - functional programming interface
 */
export const FeatureApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FeatureApiAxiosParamCreator(configuration)
    return {
        /**
         * Return a list of Feature entries
         * @summary Feature@index
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async featureIndex(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FeatureIndex200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.featureIndex(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FeatureApi.featureIndex']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FeatureApi - factory interface
 */
export const FeatureApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FeatureApiFp(configuration)
    return {
        /**
         * Return a list of Feature entries
         * @summary Feature@index
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        featureIndex(options?: RawAxiosRequestConfig): AxiosPromise<FeatureIndex200Response> {
            return localVarFp.featureIndex(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FeatureApi - object-oriented interface
 */
export class FeatureApi extends BaseAPI {
    /**
     * Return a list of Feature entries
     * @summary Feature@index
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public featureIndex(options?: RawAxiosRequestConfig) {
        return FeatureApiFp(this.configuration).featureIndex(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ProjectUsersApi - axios parameter creator
 */
export const ProjectUsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Invite multiple users and attach them to a project
         * @summary Bulk invite Project Users
         * @param {ProjectUsersBulkInviteProjectUsersRequest} projectUsersBulkInviteProjectUsersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectUsersBulkInviteProjectUsers: async (projectUsersBulkInviteProjectUsersRequest: ProjectUsersBulkInviteProjectUsersRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectUsersBulkInviteProjectUsersRequest' is not null or undefined
            assertParamExists('projectUsersBulkInviteProjectUsers', 'projectUsersBulkInviteProjectUsersRequest', projectUsersBulkInviteProjectUsersRequest)
            const localVarPath = `/api/v1/project_users/bulk`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(projectUsersBulkInviteProjectUsersRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProjectUsersApi - functional programming interface
 */
export const ProjectUsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProjectUsersApiAxiosParamCreator(configuration)
    return {
        /**
         * Invite multiple users and attach them to a project
         * @summary Bulk invite Project Users
         * @param {ProjectUsersBulkInviteProjectUsersRequest} projectUsersBulkInviteProjectUsersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async projectUsersBulkInviteProjectUsers(projectUsersBulkInviteProjectUsersRequest: ProjectUsersBulkInviteProjectUsersRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.projectUsersBulkInviteProjectUsers(projectUsersBulkInviteProjectUsersRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectUsersApi.projectUsersBulkInviteProjectUsers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProjectUsersApi - factory interface
 */
export const ProjectUsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProjectUsersApiFp(configuration)
    return {
        /**
         * Invite multiple users and attach them to a project
         * @summary Bulk invite Project Users
         * @param {ProjectUsersBulkInviteProjectUsersRequest} projectUsersBulkInviteProjectUsersRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectUsersBulkInviteProjectUsers(projectUsersBulkInviteProjectUsersRequest: ProjectUsersBulkInviteProjectUsersRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.projectUsersBulkInviteProjectUsers(projectUsersBulkInviteProjectUsersRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProjectUsersApi - object-oriented interface
 */
export class ProjectUsersApi extends BaseAPI {
    /**
     * Invite multiple users and attach them to a project
     * @summary Bulk invite Project Users
     * @param {ProjectUsersBulkInviteProjectUsersRequest} projectUsersBulkInviteProjectUsersRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public projectUsersBulkInviteProjectUsers(projectUsersBulkInviteProjectUsersRequest: ProjectUsersBulkInviteProjectUsersRequest, options?: RawAxiosRequestConfig) {
        return ProjectUsersApiFp(this.configuration).projectUsersBulkInviteProjectUsers(projectUsersBulkInviteProjectUsersRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * QueryApi - axios parameter creator
 */
export const QueryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Query the registry by Digital Identifier. Authenticated via x-client-id/x-signature headers (Custodian client credential + HMAC-signed payload), not a bearer token.
         * @summary Query@query
         * @param {string} xClientId Custodian client ID used to authenticate the requesting custodian
         * @param {string} xSignature HMAC signature of the raw request body, signed with the custodian\&#39;s unique identifier
         * @param {QueryQueryRequest} queryQueryRequest Query definition
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryQuery: async (xClientId: string, xSignature: string, queryQueryRequest: QueryQueryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xClientId' is not null or undefined
            assertParamExists('queryQuery', 'xClientId', xClientId)
            // verify required parameter 'xSignature' is not null or undefined
            assertParamExists('queryQuery', 'xSignature', xSignature)
            // verify required parameter 'queryQueryRequest' is not null or undefined
            assertParamExists('queryQuery', 'queryQueryRequest', queryQueryRequest)
            const localVarPath = `/api/v1/query`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (xClientId != null) {
                localVarHeaderParameter['x-client-id'] = String(xClientId);
            }
            if (xSignature != null) {
                localVarHeaderParameter['x-signature'] = String(xSignature);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(queryQueryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QueryApi - functional programming interface
 */
export const QueryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QueryApiAxiosParamCreator(configuration)
    return {
        /**
         * Query the registry by Digital Identifier. Authenticated via x-client-id/x-signature headers (Custodian client credential + HMAC-signed payload), not a bearer token.
         * @summary Query@query
         * @param {string} xClientId Custodian client ID used to authenticate the requesting custodian
         * @param {string} xSignature HMAC signature of the raw request body, signed with the custodian\&#39;s unique identifier
         * @param {QueryQueryRequest} queryQueryRequest Query definition
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async queryQuery(xClientId: string, xSignature: string, queryQueryRequest: QueryQueryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryQuery200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.queryQuery(xClientId, xSignature, queryQueryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QueryApi.queryQuery']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QueryApi - factory interface
 */
export const QueryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QueryApiFp(configuration)
    return {
        /**
         * Query the registry by Digital Identifier. Authenticated via x-client-id/x-signature headers (Custodian client credential + HMAC-signed payload), not a bearer token.
         * @summary Query@query
         * @param {string} xClientId Custodian client ID used to authenticate the requesting custodian
         * @param {string} xSignature HMAC signature of the raw request body, signed with the custodian\&#39;s unique identifier
         * @param {QueryQueryRequest} queryQueryRequest Query definition
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryQuery(xClientId: string, xSignature: string, queryQueryRequest: QueryQueryRequest, options?: RawAxiosRequestConfig): AxiosPromise<QueryQuery200Response> {
            return localVarFp.queryQuery(xClientId, xSignature, queryQueryRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QueryApi - object-oriented interface
 */
export class QueryApi extends BaseAPI {
    /**
     * Query the registry by Digital Identifier. Authenticated via x-client-id/x-signature headers (Custodian client credential + HMAC-signed payload), not a bearer token.
     * @summary Query@query
     * @param {string} xClientId Custodian client ID used to authenticate the requesting custodian
     * @param {string} xSignature HMAC signature of the raw request body, signed with the custodian\&#39;s unique identifier
     * @param {QueryQueryRequest} queryQueryRequest Query definition
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public queryQuery(xClientId: string, xSignature: string, queryQueryRequest: QueryQueryRequest, options?: RawAxiosRequestConfig) {
        return QueryApiFp(this.configuration).queryQuery(xClientId, xSignature, queryQueryRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * VendorWebhookReceiverApi - axios parameter creator
 */
export const VendorWebhookReceiverApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Receive a webhook callback from a vendor
         * @param {string} provider Name of the vendor providing the webhook
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vendorWebhookReceiverReceive: async (provider: string, body: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'provider' is not null or undefined
            assertParamExists('vendorWebhookReceiverReceive', 'provider', provider)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('vendorWebhookReceiverReceive', 'body', body)
            const localVarPath = `/api/v1/webhooks/{provider}`
                .replace('{provider}', encodeURIComponent(String(provider)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VendorWebhookReceiverApi - functional programming interface
 */
export const VendorWebhookReceiverApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VendorWebhookReceiverApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Receive a webhook callback from a vendor
         * @param {string} provider Name of the vendor providing the webhook
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vendorWebhookReceiverReceive(provider: string, body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<VendorWebhookReceiverReceive200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.vendorWebhookReceiverReceive(provider, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VendorWebhookReceiverApi.vendorWebhookReceiverReceive']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VendorWebhookReceiverApi - factory interface
 */
export const VendorWebhookReceiverApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VendorWebhookReceiverApiFp(configuration)
    return {
        /**
         * 
         * @summary Receive a webhook callback from a vendor
         * @param {string} provider Name of the vendor providing the webhook
         * @param {object} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vendorWebhookReceiverReceive(provider: string, body: object, options?: RawAxiosRequestConfig): AxiosPromise<VendorWebhookReceiverReceive200Response> {
            return localVarFp.vendorWebhookReceiverReceive(provider, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VendorWebhookReceiverApi - object-oriented interface
 */
export class VendorWebhookReceiverApi extends BaseAPI {
    /**
     * 
     * @summary Receive a webhook callback from a vendor
     * @param {string} provider Name of the vendor providing the webhook
     * @param {object} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public vendorWebhookReceiverReceive(provider: string, body: object, options?: RawAxiosRequestConfig) {
        return VendorWebhookReceiverApiFp(this.configuration).vendorWebhookReceiverReceive(provider, body, options).then((request) => request(this.axios, this.basePath));
    }
}



